package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface LearnerEnrollmentCommand{
	String SAVE_LEARNER_ENROLLMENT = "SAVE_LEARNER_ENROLLMENT";
	String UPDATE_LEARNER_ENROLLMENT = "UPDATE_LEARNER_ENROLLMENT";
	String DELETE_LEARNER_ENROLLMENT = "DELETE_LEARNER_ENROLLMENT";
	String GET_ALL_LEARNER_ENROLLMENTS = "GET_ALL_LEARNER_ENROLLMENTS";
	String GET_LEARNER_ENROLLMENT_BY_ID = "GET_ALL_LEARNER_ENROLLMENT_ID";
	
	String GET_LEARNER_ENROLLMENTS_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_LEARNER_ENROLLMENTS_BY_SYSTEM_USER_PROFILE_SCHOOLS";
	
	String GET_LEARNER_ENROLLMENTS_BY_ACADEMIC_TERM_SCHOOL = "GET_LEARNER_ENROLLMENTS_BY_ACADEMIC_TERM_SCHOOL";

	
	
	
}
