package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface LearnerAttendanceCommand{
	String SAVE_LEARNER_ATTENDANCE = "SAVE_LEARNER_ATTENDANCE";
	String UPDATE_LEARNER_ATTENDANCE = "UPDATE_LEARNER_ATTENDANCE";
	String DELETE_LEARNER_ATTENDANCE = "DELETE_LEARNER_ATTENDANCE";
	String GET_ALL_LEARNER_ATTENDANCES = "GET_ALL_LEARNER_ATTENDANCES";
	String GET_LEARNER_ATTENDANCE_BY_ID = "GET_ALL_LEARNER_ATTENDANCE_ID";
	String GET_LEARNER_ATTENDANCE_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_LEARNER_ATTENDANCE_BY_SYSTEM_USER_PROFILE_SCHOOLS";
	
	
}
