package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface RegionDistrictCommands {
	String SAVE_REGION = "SAVE_REGION";
	String UPDATE_REGION = "UPDATE_REGION";
	String DELETE_REGION = "DELETE_REGION";
	String GET_ALL_REGIONS = "GET_ALL_REGIONS";
	String GET_REGION_BY_ID = "GET_REGION_BY_ID";
	String GET_REGIONS_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_REGIONS_BY_SYSTEM_USER_PROFILE_SCHOOLS";
	
	
	String SAVE_DISTRICT = "SAVE_DISTRICT";
	String UPDATE_DISTRICT = "UPDATE_DISTRICT";
	String DELETE_DISTRICT = "DELETE_DISTRICT";
	String GET_ALL_DISTRICTS = "GET_ALL_DISTRICTS";
	String GET_DISTRICT_BY_ID = "GET_DISTRICT_BY_ID";
	String GET_ALL_DISTRICTS_BY_REGION = "GET_ALL_DISTRICTS_BY_REGION";
	String ACTIVATE_DISTRICT = "ACTIVATE_DISTRICT";
	String DEACTIVATE_DISTRICT = "DEACTIVATE_DISTRICT";
	String GET_DISTRICTS_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_DISTRICTS_BY_SYSTEM_USER_PROFILE_SCHOOLS";
}
