package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface SchoolCategoryClassCommand{
	String SAVE_SCHOOL_CATEGORY = "SAVE_SCHOOL_CATEGORY";
	String UPDATE_SCHOOL_CATEGORY = "UPDATE_SCHOOL_CATEGORY";
	String DELETE_SCHOOL_CATEGORY = "DELETE_SCHOOL_CATEGORY";
	String GET_ALL_SCHOOL_CATEGORYS = "GET_ALL_SCHOOL_CATEGORYS";
	String GET_SCHOOL_CATEGORY_BY_ID = "GET_ALL_SCHOOL_CATEGORY_ID";
	String GET_SCHOOL_CATEGORIES_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_SCHOOL_CATEGORIES_BY_SYSTEM_USER_PROFILE_SCHOOLS";
	
	
	String SAVE_SCHOOL = "SAVE_SCHOOL";
	String UPDATE_SCHOOL = "UPDATE_SCHOOL";
	String DELETE_SCHOOL = "DELETE_SCHOOL";
	String GET_ALL_SCHOOLS = "GET_ALL_SCHOOLS";
	String GET_ALL_SCHOOLS_BY_SCHOOL_CATEGORY = "GET_ALL_SCHOOLS_BY_SCHOOL_CATEGORY";
	String GET_ALL_SCHOOLS_BY_SCHOOL_DISTRICT = "GET_ALL_SCHOOLS_BY_SCHOOL_DISTRICT";
	String GET_SCHOOL_BY_ID = "GET_SCHOOL_BY_ID";
	String GET_SCHOOLS_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_SCHOOLS_BY_SYSTEM_USER_PROFILE_SCHOOLS";
	
	
	
	String SAVE_SCHOOL_CLASS = "SAVE_SCHOOL_CLASS";
	String UPDATE_SCHOOL_CLASS = "UPDATE_SCHOOL_CLASS";
	String DELETE_SCHOOL_CLASS = "DELETE_SCHOOL_CLASS";
	String GET_ALL_SCHOOL_CLASSES = "GET_ALL_SCHOOL_CLASSES";
	String GET_ALL_SCHOOL_CLASSES_BY_SCHOOL = "GET_ALL_SCHOOL_CLASSES_BY_SCHOOL";
	String GET_SCHOOL_CLASS_BY_ID = "GET_SCHOOL_CLASS_BY_ID";
	String GET_SCHOOL_CLASSES_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_SCHOOL_CLASSES_BY_SYSTEM_USER_PROFILE_SCHOOLS";



}
