package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface SchoolStaffEnrollmentCommand{
	String SAVE_STAFF_ENROLLMENT = "SAVE_STAFF_ENROLLMENT";
	String UPDATE_STAFF_ENROLLMENT = "UPDATE_STAFF_ENROLLMENT";
	String DELETE_STAFF_ENROLLMENT = "DELETE_STAFF_ENROLLMENT";
	String GET_ALL_STAFF_ENROLLMENTS = "GET_ALL_STAFF_ENROLLMENTS";
	String GET_STAFF_ENROLLMENT_BY_ID = "GET_ALL_STAFF_ENROLLMENT_ID";
	String GET_STAFF_ENROLLMENTS_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_STAFF_ENROLLMENTS_BY_SYSTEM_USER_PROFILE_SCHOOLS";
	String GET_STAFF_ENROLLMENTS_BY_ACADEMIC_TERM_SCHOOL = "GET_STAFF_ENROLLMENTS_BY_ACADEMIC_TERM_SCHOOL";
	

	
	
	String SAVE_SCHOOL_STAFF = "SAVE_SCHOOL_STAFF";
	String UPDATE_SCHOOL_STAFF = "UPDATE_SCHOOL_STAFF";
	String DELETE_SCHOOL_STAFF = "DELETE_SCHOOL_STAFF";
	String GET_ALL_SCHOOL_STAFFS = "GET_ALL_SCHOOL_STAFFS";
	String GET_SCHOOL_STAFF_BY_ID = "GET_SCHOOL_STAFF_BY_ID";
	String ACTIVATE_SCHOOL_STAFF = "ACTIVATE_SCHOOL_STAFF";
	String DEACTIVATE_SCHOOL_STAFF = "DEACTIVATE_SCHOOL_STAFF";
	String GET_SCHOOL_STAFFS_BY_ACADEMIC_TERM_SCHOOL = "GET_SCHOOL_STAFFS_BY_ACADEMIC_TERM_SCHOOL";
	String GET_SCHOOL_STAFFS_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_SCHOOL_STAFFS_BY_SYSTEM_USER_PROFILE_SCHOOLS";
	
	
	
}
