package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface StaffDailyTimetableCommand{
	String SAVE_STAFF_DAILY_TIME_TABLE = "SAVE_STAFF_DAILY_TIME_TABLE";
	String UPDATE_STAFF_DAILY_TIME_TABLE = "UPDATE_STAFF_DAILY_TIME_TABLE";
	String DELETE_STAFF_DAILY_TIME_TABLE = "DELETE_STAFF_DAILY_TIME_TABLE";
	String GET_ALL_STAFF_DAILY_TIME_TABLES = "GET_ALL_STAFF_DAILY_TIME_TABLES";
	String GET_STAFF_DAILY_TIME_TABLE_BY_ID = "GET_ALL_STAFF_DAILY_TIME_TABLE_ID";
	
	
	String GET_STAFF_DAILY_TIME_TABLES_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_STAFF_DAILY_TIME_TABLES_BY_SYSTEM_USER_PROFILE_SCHOOLS";
	
}
