package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface StaffDailySupervisionCommand{
	String SAVE_STAFF_DAILY_SUPERVISION = "SAVE_STAFF_DAILY_SUPERVISION";
	String UPDATE_STAFF_DAILY_SUPERVISION = "UPDATE_STAFF_DAILY_SUPERVISION";
	String DELETE_STAFF_DAILY_SUPERVISION = "DELETE_STAFF_DAILY_SUPERVISION";
	String GET_ALL_STAFF_DAILY_SUPERVISIONS = "GET_ALL_STAFF_DAILY_SUPERVISIONS";
	String GET_STAFF_DAILY_SUPERVISION_BY_ID = "GET_ALL_STAFF_DAILY_SUPERVISION_ID";
	String GET_STAFF_DAILY_SUPERVISIONS_BY_SYSTEM_USER_PROFILE_SCHOOLS_SCHOOL_DATE = "GET_STAFF_DAILY_SUPERVISIONS_BY_SYSTEM_USER_PROFILE_SCHOOLS_SCHOOL_DATE";

}
