package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface StaffDailyTimetableLessonCommands{	
	String SAVE_STAFF_DAILY_TIME_TABLE_LESSON = "SAVE_STAFF_DAILY_TIME_TABLE_LESSON";
	String UPDATE_STAFF_DAILY_TIME_TABLE_LESSON = "UPDATE_STAFF_DAILY_TIME_TABLE_LESSON";
	String DELETE_STAFF_DAILY_TIME_TABLE_LESSON = "DELETE_STAFF_DAILY_TIME_TABLE_LESSON";
	String GET_ALL_STAFF_DAILY_TIME_TABLE_LESSONS = "GET_ALL_STAFF_DAILY_TIME_TABLE_LESSONS";
	String GET_STAFF_DAILY_TIME_TABLES_LESSONS_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_STAFF_DAILY_TIME_TABLES_LESSONS_BY_SYSTEM_USER_PROFILE_SCHOOLS";
		
}
