package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface SubjectCategoryCommand{
	String SAVE_SUBJECT_CATEGORY = "SAVE_SUBJECT_CATEGORY";
	String UPDATE_SUBJECT_CATEGORY = "UPDATE_SUBJECT_CATEGORY";
	String DELETE_SUBJECT_CATEGORY = "DELETE_SUBJECT_CATEGORY";
	String GET_ALL_SUBJECT_CATEGORYS = "GET_ALL_SUBJECT_CATEGORYS";
	String GET_SUBJECT_CATEGORY_BY_ID = "GET_ALL_SUBJECT_CATEGORY_ID";
	
	
	String SAVE_SUBJECT = "SAVE_SUBJECT";
	String UPDATE_SUBJECT = "UPDATE_SUBJECT";
	String DELETE_SUBJECT = "DELETE_SUBJECT";
	String GET_ALL_SUBJECTS = "GET_ALL_SUBJECTS";
	String GET_ALL_SUBJECTS_BY_SUBJECT_CATEGORY = "GET_ALL_SUBJECTS_BY_SUBJECT_CATEGORY";
	String GET_SUBJECT_BY_ID = "GET_SUBJECT_BY_ID";
	
}
