package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface SystemUserProfileSchoolCommand{
	String SAVE_SYSTEM_USER_PROFILE_SCHOOLS = "SAVE_SYSTEM_USER_PROFILE_SCHOOLS";
	String UPDATE_SYSTEM_USER_PROFILE_SCHOOL = "UPDATE_SYSTEM_USER_PROFILE_SCHOOL";
	String DELETE_SYSTEM_USER_PROFILE_SCHOOLS = "DELETE_SYSTEM_USER_PROFILE_SCHOOLS";
	String GET_ALL_SYSTEM_USER_PROFILE_SCHOOLS = "GET_ALL_SYSTEM_USER_PROFILE_SCHOOLS";
	String GET_SYSTEM_USER_PROFILE_SCHOOL_SCHOOLS_BY_ID = "GET_ALL_SYSTEM_USER_PROFILE_SCHOOL_ID";
	String GET_NOT_PROFILE_SCHOOLS_BY_PROFILE_DISTRICT = "GET_NOT_PROFILE_SCHOOLS_BY_PROFILE_DISTRICT";
		
	
}
