package com.planetsystems.tela.managementapp.shared.requestcommands;

public interface TimetableLessonCommands{	
	String SAVE_TIMETABLE_LESSON = "SAVE_TIMETABLE_LESSON";
	String UPDATE_TIMETABLE_LESSON = "DELETE_TIMETABLE_LESSON";
	String DELETE_TIMETABLE_LESSONS = "DELETE_TIMETABLE_LESSONS";
	String GET_ALL_TIMETABLE_LESSONS = "GET_ALL_TIMETABLE_LESSONS";
	String GET_TIMETABLE_LESSONS_BY_SYSTEM_USER_PROFILE_SCHOOLS = "GET_TIMETABLE_LESSONS_BY_SYSTEM_USER_PROFILE_SCHOOLS";
	String DELETE_TIMETABLE_LESSON = "DELETE_TIMETABLE_LESSON";
	String GET_ALL_TIMETABLE_LESSONSBY_ID = "GET_ALL_TIMETABLE_LESSONSBY_ID";
	String DELETE_TIMETABLE_LESSON_BY_ID = "DELETE_TIMETABLE_LESSON_BY_ID";
		
}
