package com.planetsystems.tela.managementapp.shared.requestconstants;

public interface SystemUserProfileRequestConstant {
	String SAVE_SYSTEM_USER_PROFILE = "SAVE_SYSTEM_USER_PROFILE";
	String GET_SYSTEM_USER_PROFILES = "GET_SYSTEM_USER_PROFILES";
	String UPDATE_SYSTEM_USER_PROFILE = "UPDATE_SYSTEM_USER_PROFILE";
	String DELETE_SYSTEM_USER_PROFILE = "DELETE_SYSTEM_USER_PROFILE";
	
	String DEACTIVATE_SYSTEM_USER_PROFILE = "DEACTIVATE_SYSTEM_USER_PROFILE";
	
	String ACTIVATE_SYSTEM_USER_PROFILE = "ACTIVATE_SYSTEM_USER_PROFILE";
	
	String RESET_PASSWORD_SYSTEM_USER_PROFILE = "RESET_PASSWORD_SYSTEM_USER_PROFILE";
	
	String UPDATE_LOGGED_SYSTEM_USER_PROFILE_DETAILS = "UPDATE_LOGGED_SYSTEM_USER_PROFILE_DETAILS";
	String GET_SYSTEM_USER_PROFILE = "GET_SYSTEM_USER_PROFILE";
	
	String DATA = "DATA";
	

}
