package com.planetsystems.tela.managementapp.shared;

public interface RequestDelimeters {
  String ACADEMIC_YEAR_ID = "ACADEMIC_YEAR_ID";
  String ACADEMIC_TERM_ID = "ACADEMIC_TERM_ID";
  String REGION_ID = "REGION_ID";
  String DISTRICT_ID = "DISTRICT_ID";
  String SCHOOL_ID = "SCHOOL_ID";
  String SCHOOL_CATEGORY_ID = "SCHOOL_CATEGORY_ID";
  String SCHOOL_STAFF_ID = "SCHOOL_STAFF_ID";
  String SUBJECT_CATEGORY_ID = "SUBJECT_CATEGORY_ID";
  String SUBJECT_ID = "SUBJECT_ID";
  String ATTENDANCE_DATE = "ATTENDANCE_DATE";
//  String DAY = "DAY";
  String SCHOOL_CLASS_ID = "SCHOOL_CLASS_ID";
  
String STAFF_ENROLLMENT_ID = "STAFF_ENROLLMENT_ID";
String LEARNER_ENROLLMENT_ID = "LEARNER_ENROLLMENT_ID";
String CLOCKIN_DATE = "CLOCKIN_DATE";
String CLOCK_OUT_DATE = "CLOCK_OUT_DATE";
String CLOCK_IN_ID = "CLOCK_IN_ID";
String CLOCK_OUT_ID = "CLOCK_OUT_ID";
String LEARNER_ATTENDANCE_ID = "LEARNER_ATTENDANCE_ID";
String TIME_TABLE_ID = "TIME_TABLE_ID";
String SUPERVISION_DATE = "SUPERVISION_DATE";
String STAFF_TIMETABLE_LESSON_ID = "STAFF_TIMETABLE_LESSON_ID";
String STAFF_DAILY_ATTENDANCE_SUPERVISION_ID = "STAFF_DAILY_ATTENDANCE_SUPERVISION_ID";
String ABSENT_DATE = "ABSENT_DATE";
String FILTER_SCHOOL = "FILTER_SCHOOL";
String FILTER_SCHOOL_CLASS = "FILTER_SCHOOL_CLASS";
String FILTER_LEARNER_ATTENDANCES = "FILTER_LEARNER_ATTENDANCES";
String FILTER_LEARNER_ENROLLEMENTS = "FILTER_LEARNER_ENROLLEMENTS";
String FILTER_CLOCK_INS = "FILTER_CLOCK_INS";
String FILTER_CLOCK_OUTS = "FILTER_CLOCK_OUTS";
String FILTER_STAFF_ENROLLMENTS = "FILTER_STAFF_ENROLLMENTS";
String FILTER_SCHOOL_STAFFS = "FILTER_SCHOOL_STAFFS";
String LESSON_DAY = "LESSON_DAY";
String TIME_TABLE_LESSON_ID = "TIME_TABLE_LESSON_ID";
String LESSON_DATE = "LESSON_DATE";
String STAFF_DAILY_TIMETALE_ID = "STAFF_DAILY_TIMETALE_ID";

String SYSTEM_USER_PROFILE_ID = "SYSTEM_USER_PROFILE_ID";
String SYSTEM_USER_GROUP_ID = "SYSTEM_USER_GROUP_ID";
String FILTER_DATA = "FILTER_DATA"; 

String EXPORT_SCHOOL_STAFFS = "EXPORT_SCHOOL_STAFFS";
  
}
